-- MySQL Script generated by MySQL Workbench
-- Fri Jan  1 10:37:09 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema missa
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema missa
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `missa` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema new_schema1
-- -----------------------------------------------------
USE `missa` ;

-- -----------------------------------------------------
-- Table `missa`.`members`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `missa`.`members` ;

CREATE TABLE IF NOT EXISTS `missa`.`members` (
  `members_id` INT NOT NULL AUTO_INCREMENT,
  `members_name` VARCHAR(45) NOT NULL,
  `members_email` VARCHAR(45) NOT NULL,
  `members_phone` VARCHAR(15) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `register_date` DATETIME NOT NULL,
  `members_status` INT NOT NULL,
  PRIMARY KEY (`members_id`),
  UNIQUE INDEX `email_UNIQUE` (`members_email` ASC),
  UNIQUE INDEX `user_id_UNIQUE` (`members_id` ASC),
  UNIQUE INDEX `members_phone_UNIQUE` (`members_phone` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `missa`.`Product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `missa`.`Product` ;

CREATE TABLE IF NOT EXISTS `missa`.`Product` (
  `product_id` INT NOT NULL AUTO_INCREMENT,
  `productcol` VARCHAR(45) NOT NULL,
  `picture` BLOB NOT NULL,
  `price` INT NOT NULL,
  `members_email` VARCHAR(45) NOT NULL,
  `reservaed_times` INT NULL,
  `square` FLOAT NOT NULL,
  `location` VARCHAR(45) NOT NULL,
  `elevator` TINYINT(1) NOT NULL,
  `layout` VARCHAR(45) NOT NULL,
  `detail` VARCHAR(45) NULL,
  `age` FLOAT NOT NULL,
  `haunted` TINYINT(1) NOT NULL,
  `tracked_times` INT NULL,
  PRIMARY KEY (`product_id`),
  UNIQUE INDEX `id_UNIQUE` (`product_id` ASC),
  UNIQUE INDEX `user_user_email_UNIQUE` (`members_email` ASC),
  CONSTRAINT `fk_product_user_email`
    FOREIGN KEY (`members_email`)
    REFERENCES `missa`.`members` (`members_email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `missa`.`tracking_list`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `missa`.`tracking_list` ;

CREATE TABLE IF NOT EXISTS `missa`.`tracking_list` (
  `tracking_id` INT NOT NULL AUTO_INCREMENT,
  `members_email` VARCHAR(45) NOT NULL,
  `product_id` INT NOT NULL,
  INDEX `fk_trail_members_idx` (`members_email` ASC),
  PRIMARY KEY (`tracking_id`),
  CONSTRAINT `fk_tracking_listl_members`
    FOREIGN KEY (`members_email`)
    REFERENCES `missa`.`members` (`members_email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `missa`.`reservation_list`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `missa`.`reservation_list` ;

CREATE TABLE IF NOT EXISTS `missa`.`reservation_list` (
  `reservation_id` INT NOT NULL AUTO_INCREMENT,
  `members_email` VARCHAR(45) NOT NULL,
  `reservation_date` DATE NOT NULL,
  `product_id` INT NOT NULL,
  PRIMARY KEY (`reservation_id`),
  CONSTRAINT `fk_reservation_list_has_members_email`
    FOREIGN KEY (`members_email`)
    REFERENCES `missa`.`members` (`members_email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `missa`.`property_right`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `missa`.`property_right` ;

CREATE TABLE IF NOT EXISTS `missa`.`property_right` (
  `land_right_img` BLOB NOT NULL,
  `house_right_img` BLOB NOT NULL,
  `id_card_right` BLOB NOT NULL,
  `id_card_left` BLOB NOT NULL,
  `product_id` INT NOT NULL,
  PRIMARY KEY (`product_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
